name: Generar Documentacion
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: 
        python -m pip install --upgrade pip
        pip install pdoc3
        
    - name: Create docs directory
      run: mkdir -p docs
      
    - name: Generate HTML documentation
      run: python -m pdoc --html main.py -o docs/html
      
    - name: Generate text documentation
      run: python -m pydoc main > docs/main.txt
      
    - name: Upload HTML documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: html-documentation
        path: docs/html/
        
    - name: Upload text documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: text-documentation
        path: docs/main.txt